version: '3.8'

services:
  dataapi:
    image: dataapi-image
    build:
      context: ./DataAPI
      dockerfile: Dockerfile
    ports:
      - "5234:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - database

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Traxler99.
      MYSQL_DATABASE: exchangeratedb
      MYSQL_USER: omercan
      MYSQL_PASSWORD: Traxler99.
    ports:
      - "3306:3306"
